### ISSUE TITLE
Games that do not start

### ISSUE THREAD

**Issue by niasuniasu** [zwenergy/swancolorHD#1]
I tried several games and SAINT SEIYA and DRAGON BALL would not start.
And all the games with vertical display, such as GUNPEY and TETRIS, do not start.
What could be the cause?

**Comment by niasuniasu** [comment]
After turning on the micro USB 5V power supply, when I turned on the WonderSwan unit, the game that did not start up started up.
Most games will start just by turning on the micro USB 5V power supply, so I would like to be able to start games in the same way, is there a solution?

**Comment by zwenergy** [comment]
So far I haven't heard of anything like this, I tried Tetris and it works for me without problems. I don't fully get your description, how do you turn on the WonderSwan while being consolized?

Besides, did you try to play the games from a "cold boot" or after you already played something (so turn off the consolizer, change the game and directly turn it on again?

**Comment by niasuniasu** [comment]
![_20240607_034853](https://github.com/zwenergy/swancolorHD/assets/100687301/eb588d37-0a26-4905-91a6-ab903e74b918)

Currently, the power is turned on and off with a micro USB cable with a switch.
When the USB cable is switched on, the WonderSwan unit turns on and the game starts.

I removed the Q8 2N7002 from the consolizer board and it started the game that did not start.
